// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.dfs.namenode.rpc.model;

public interface MkdirRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dfs.namenode.rpc.MkdirRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1;</code>
   */
  String getPath();
  /**
   * <code>string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
