// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.dfs.namenode.rpc.model;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dfs.namenode.rpc.RegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string hostname = 2;</code>
   */
  String getHostname();
  /**
   * <code>string hostname = 2;</code>
   */
  com.google.protobuf.ByteString
      getHostnameBytes();
}
